### ISSUE TITLE
Browser icon doesn't appear to scale completely

### ISSUE THREAD

**Issue by spekulatius** [astrit/css.gg#10]
Hello @astrit,

I've tried to scale the browser icon up using CSS. One of the lines didn't scale proper:

![image](https://user-images.githubusercontent.com/8433587/71495520-e61ff380-2880-11ea-99d4-23b710ca54fe.png)

This is what I've applied:

![image](https://user-images.githubusercontent.com/8433587/71495590-339c6080-2881-11ea-81ab-35d971d6666b.png)

Just thought I let you know :)

Peter

**Comment by anskydev** [comment]
You are right, this should be fixed by updating `.gg-browser::before`:

```
.gg-browser::before {
   width: 22px; // before
   width: 100%; // new
}
```

**Comment by spekulatius** [comment]
Ah, awesome @anskydev. Should I open a PR or do you want to ?

**Comment by astrit** [comment]
@spekulatius didn't you try to resize with --ggs variable ? 
Or you want to later the design ?

**Comment by spekulatius** [comment]
Hey @astrit and @anskydev 

Happy New Year!

Astrit, with -ggs it works as expected. It's kinda a habit to do it using Tailwind classes.

Peter

**Comment by anskydev** [comment]
Hello guys, happy new year to you too!

I have some free time to look into this PR to fix the icon but I would like to discuss some off-topic development aspects with @astrit first: 

1) I think it would be better to use NPM to build the various packages: the main file could be **icons.sass**, (this is where **issue 2** begins) and we use node to build the rest (icons.css, icons.xml, icons.json) from this file.

2) I feel the sass file is not optimized enough and its more "css inside sass" than a real sass file, also compare the file size of all css files (290kb) vs a single sass file (297kb). I think we could follow the same structure as css and have a file per icon, and the main file will only import the icons, that will facilitate modular import in other projects. Also we can have common placeholders of properties that repeat all along all the classes (border-box, display: block, etc...).

The purpose of this is to keep consistency along the files, so you don't have to update all of them one by one.

Tell me if this sounds like a good idea and I will gladly help you with it.

**Comment by spekulatius** [comment]
Okay @anskydev. Interesting questions, btw. I'm keen to hear @astrit thoughts.

**Comment by astrit** [comment]
@anskydev I agree with most things. 
I was planning on to have every icon as .scss, .sass, .less generated automatically so there is more coverage. 

I am not very much experienced but would love to find a middle ground for Angular, Vue and React and that way would be very easy for people to include on all their projects. 

icons.sass could have common placeholders but not the single icon so yeah that makes a lot of sense, how ever for the moment are too many things going on and will take time to implement. 

If you are available for help please join here: 
https://discord.gg/e7NDKFM and will discuss it there. 

Thank you very much.
