### ISSUE TITLE
css.gg firefox bug for svg glyf-bar

### ISSUE THREAD

**Issue by Mil1** [astrit/css.gg#100]
Hello,

I use our super css.gg app in Firefox and is broken due to SvG in your new top bar link.The SVG take all the page and is impossible to navigati in the app.

Firefox can't support the LH unit : https://caniuse.com/?search=lh%20unit

Thank you

**Comment by astrit** [comment]
Thank you very much for letting me know. 
This is epic, I did not check if Firefox supports it, good catch. 

It is fixed now, let me know if it looks good on your end.

**Comment by Mil1** [comment]
Is working well !
