### ISSUE TITLE
BUG: Error 404 on https://css.gg/css

### ISSUE THREAD

**Issue by Zagur** [astrit/css.gg#110]
I have a website where I use icons and today I noticed that they are not showing up. Checking the Firefox console, I saw that the link https://css.gg/css gives a 404 error.

I use it in the following way:

```
<!-- CSS Format -->
<link href="https://css.gg/css?= {ICONNAME} | {ICONNAME}" rel="stylesheet" />
```

```
$ curl -I https://css.gg/css
HTTP/2 404 
access-control-allow-origin: *
age: 12636
cache-control: public, max-age=0, must-revalidate
content-disposition: inline; filename="404"
content-type: text/html; charset=utf-8
date: Sat, 10 Aug 2024 15:42:04 GMT
etag: "f0ef0f62d48ff7f4ea6eb249622e9462"
server: Vercel
strict-transport-security: max-age=63072000
x-matched-path: /404
x-vercel-cache: HIT
x-vercel-id: cdg1::mgpk8-1723304524681-159ab878a3b3
content-length: 12845
``` 

![image](https://github.com/user-attachments/assets/89cf54a9-6186-46a5-a57d-444e36fc32a9)

**Comment by astrit** [comment]
Hi @Zagur 

Unfortunately recently has been some developments and one of those being that the expenses had skyrocketed, I had to convert the site to a static one and host on Github Pages.

You might have noticed past weeks the project went offline several times.

As a result that functionality is no longer supported, you can still copy a single icon directly from the site.

Hope this helps!
