### ISSUE TITLE
I am unable to import the css of cart icon

### ISSUE THREAD

**Issue by iamjayshree** [astrit/css.gg#111]
I have been using css.gg for some time and I absolutely love it.

I am building a minimal e-commerce website today so I decided to use the cart icon.

but when I click on it nothing happens, I remember we used to get a code copying field and import options but it just refreshes.

Browser is: Mozilla Firefox.

I have attached a video, showcasing my issue as well. 

https://github.com/user-attachments/assets/7319833b-edc8-4841-940a-2f1459b45dbb

**Comment by astrit** [comment]
Hi @iamjayshree 

Unfortunately recently has been some developments and one of those being that the expenses had skyrocketed and unfortunately had to convert the site to a static one and host on Github Pages. 

You might have noticed past weeks the project went offline several times. 

As a result that functionality is no longer supported, you can still copy a single icon directly from the site and paste it into a new .css file. 

Hope this helps! 

FYI I am working on something to make a permanent solution but can't promise that this feature will be back.

**Comment by iamjayshree** [comment]
Thanks for the reply @astrit , i hope things get better and we get the OG css.gg back.

**Comment by astrit** [comment]
> Thanks for the reply @astrit , i hope things get better and we get the OG css.gg back. 

Hopefully but you can still get the inline style

https://css.gg/icon/shopping-cart/css

And copy to clipboard check the shortcuts there are some options
