### ISSUE TITLE
inconsistencies between browsers and zoom levels

### ISSUE THREAD

**Issue by sammax** [astrit/css.gg#16]
Some icons are inconsistent and broken in different browsers and at different zoom levels. 
There's also inconsistencies between viewing them on my 4k screen at 125% DPI scaling or on my 1080p screen at 100% DPI scaling. Since you advertise your icons as both accessible and retina-ready, they should work consistently across all zoom levels and on all DPI scalings.

Here is an imgur album that demonstrates the issue: [https://imgur.com/a/wGqacsx](https://imgur.com/a/wGqacsx)

**Comment by astrit** [comment]
Now we have SVG version so CSS will stay as it is since there is no other solution to zoom.
