### ISSUE TITLE
CSS vs SVG for icons

### ISSUE THREAD

**Issue by LifeIsStrange** [astrit/css.gg#17]
Hi!
This is just out of curiosity, 
What are the pro and cons of using CSS over SVG for icons? And vice-versa.

Anyway, thank you for this useful project!

**Comment by Calinou** [comment]
The first item of the [FAQ](https://css.gg/faq) explains this. That said, keep in mind you can also inline SVG icons, so I'm not sure if **6.** in that list is actually a benefit compared to SVG :slightly_smiling_face:

**Comment by LifeIsStrange** [comment]
thanks :)
