### ISSUE TITLE
Icon request : Hide icon

### ISSUE THREAD

**Issue by Icare666** [astrit/css.gg#20]
Hello,
Would it be possible to you to create a hide icon ? By that, I mean to take the eye icon which already exists, and cross it out.
If you create it, it would go complete the eye icon if someone want to use icons for a password input to reveal or hide the text, for instance.
Thanks in advance !

**Comment by astrit** [comment]
That is a good idea, will try to make it happen.
Can't say for sure if possible because that shape is a bit hard to do.

**Comment by Icare666** [comment]
Thank you very much 😇

**Comment by astrit** [comment]
@Icare666 I have tried several times, but unfortunately with the system in place is not possible to do a cross line currently how ever you can edit the SVG version now if you like.

Unfortunately closing this issue.
