### ISSUE TITLE
I create a styled-components version

### ISSUE THREAD

**Issue by JiangWeixian** [astrit/css.gg#25]
hey, i convert css.gg to styled-components, i hope that helps. https://github.com/JiangWeixian/styled-cssgg

**Comment by astrit** [comment]
Holly smokes, can I use this and add it to main repo ? 

Or perhaps you can do a PR

**Comment by JiangWeixian** [comment]
check this https://github.com/astrit/css.gg/pull/26

**Comment by astrit** [comment]
Awesome, will merge asap with the 200 new icons coming hopefully next week.

Is there any option that helps me build the 200 new icons or I should do it manually ?

**Comment by JiangWeixian** [comment]
you can `npm run build` under `icons-styled-components` folder.

this script will extract icons-json, and then convert it to styled-components
