### ISSUE TITLE
Any idea to add scss support too?

### ISSUE THREAD

**Issue by peiris** [astrit/css.gg#4]
Just wondering If you have plans to add scss file too in addition to css file. that would come in handy when working with angular/react projects.

**Comment by astrit** [comment]
At this state is too much work to convert every icon but I am thinking to do it as a single file for all of them.

If you have any idea regarding this please let me know.

**Comment by hunzaboy** [comment]
I have a pull request regarding this issue.

**Comment by astrit** [comment]
> I have a pull request regarding this issue.

That is awesome, will definitely merge to master ASAP.
