### ISSUE TITLE
Icons in React

### ISSUE THREAD

**Issue by KirdesMF** [astrit/css.gg#43]
Good morning, sir,
I just started a new project and I'm starting to use css.gg.
I use `React `and` styled-component.`
I've made a `codesandbox`  to show how, maybe, we could import these Icons into React.
I know there are already component style based Icons but they should, however, be more customizable.
It's just an approach that I think needs to be improved.
I also noticed that there are no title tags in the svg.
Thanks for the work.
Good continuation.

here is the codesandbox :

https://codesandbox.io/s/cssgg-styled-react-hdhtc?file=/src/App.tsx

**Comment by astrit** [comment]
Will review and get back to you ASAP

**Comment by KirdesMF** [comment]
I've modified the codesandbox.
