### ISSUE TITLE
Update license

### ISSUE THREAD

**Issue by ImedAdel** [astrit/css.gg#6]
Hello! Great Project!

I really liked the way you handled the pricing for this project but I don't think that an MIT license is suitable here?

I'm looking to build projects with the same pricing structure and I hoped that you found a solution for which license to use 😸

**Comment by anskydev** [comment]
> The pricing for the project?

Am I missing something? @astrit released this package under MIT and he is just asking for donations, why the need to update from such a permissive license?

**Comment by astrit** [comment]
> Hello! Great Project!
> 
> I really liked the way you handled the pricing for this project but I don't think that an MIT license is suitable here?
> 
> I'm looking to build projects with the same pricing structure and I hoped that you found a solution for which license to use 😸

This is free man if you like to be a sponsor then you can donate on paypal.me/astrit otherwise it will always be MIT and always free. 

@ImedAdel you are correct. It clearly notes SPONSOR

**Comment by ImedAdel** [comment]
@astrit I thought the license was "free for personal and free projects, paid for commercial ones". Which is why I asked...

**Comment by anskydev** [comment]
You can check license permissions of a GitHub project at "Code" tab and the last link on the code information bar will be the name of the license, MIT in this case or usually there is a LICENSE file at the root.

https://github.com/astrit/css.gg/blob/master/LICENSE

**Comment by ImedAdel** [comment]
@anskydev I know. But check this page: https://css.gg/price

**Comment by anskydev** [comment]
@ImedAdel yes, you are right, the "pricing" page of the website is a little bit confusing, and "paid for commercial use" also since the license already grants you that. Anyways, I always stick to what a project's license says.

**Comment by astrit** [comment]
@ImedAdel , @anskydev actually you both are right, this seems a bit confusing any suggestions to improve it ? 

Because what that is is simply Sponsorship for this repo nothing more , or on a sense Donation, or perhaps I should remove the pricing page all together and just write donation ?

**Comment by astrit** [comment]
I have updated the text on this page: 
https://css.gg/price

**Comment by anskydev** [comment]
I like the new pricing page, and the message is much cleaner now, well done @astrit!
