### ISSUE TITLE
Figma design issue: Some icon components have a 180degree rotate property

### ISSUE THREAD

**Issue by colourbound** [astrit/css.gg#74]
Some icon master components have a 180degree rotate property.

**EDIT:** On top of this some icons have been flipped vertically

**Icons affected:**
- Every icon in the "Other" category from "Plug" downwards.

**Why is this a problem:**
Because the rotation is on the master component when swapping between different icons (some with and some without the 180 degree property) the icons will flip. Currently everyone who duplicates the file will need to manually fix this themselves.

For icons that have been flipped it means using them with other icon systems will flip them when swapped inside a component.

**How to fix:**
Reset the master component degree property to 0 and change internal vector path degree property to meet the needs of the individual icon (usually also resetting it to 0).

Flip any affected icon so the Y co-ordinate is the lower of the two.

![Screen Shot 2021-08-20 at 11 01 20 am](https://user-images.githubusercontent.com/8970677/130162714-22569836-8959-4184-9be7-1e99ca86701f.png)

![Screen Shot 2021-08-20 at 11 33 27 am](https://user-images.githubusercontent.com/8970677/130165061-9af58f9b-d293-4197-b7be-0f0c43cea49f.png)

**Comment by astrit** [comment]
Thank you very much for this, I did not know this is an issue. Will try and fix it as soon as possible.
