### ISSUE TITLE
Broken border-top icon

### ISSUE THREAD

**Issue by ilyasmez** [astrit/css.gg#88]
The border-top icon uses a hardcoded value for one of it's paths' fills, instead of `currentColor`:
https://github.com/astrit/css.gg/blob/master/icons/svg/border-top.svg?short_path=fd205a6#L13

Compared to, for example, border-bottom:
https://github.com/astrit/css.gg/blob/master/icons/svg/border-bottom.svg?short_path=6098ab3#L9

This results in the path not having a fill when used from react-icons:
<img width="376" alt="react icons screenshot" src="https://user-images.githubusercontent.com/30146019/178748980-239599dd-df50-445c-8675-f630de1f555a.png">

or having a fill that is hard to change when using the SVG directly.

**Comment by niprestige** [comment]
Is this issue still open? I would like to contribute

**Comment by astrit** [comment]
@ilyasmez thank you very much for reporting this, it has been fixed now. Sorry for late reply.
