### ISSUE TITLE
Bug: css.gg is empty

### ISSUE THREAD

**Issue by bangank36** [astrit/css.gg#95]
## Summary
- When access the homepage https://css.gg/ there is no icons and other content
![chrome-capture-2023-4-5 (1)](https://user-images.githubusercontent.com/10071857/236464900-c84da684-0a5d-48f7-95fd-e82719f508b2.png)

**Comment by astrit** [comment]
Sorry for the late reply, this was due to a server issue which now has been fixed, much appreciated that you took the time to report it.
