### ISSUE TITLE
Adding text next to icon when using <i> results in a line break

### ISSUE THREAD

**Issue by elburro1887** [astrit/css.gg#96]
When i add a text next to any icon when using `<i>`, I will get a line break between the text and the icon

`<p><i class='gg-software-download'></i>Download</p>`

Maybe this is intended behavior, but in all other icon libraries, there is no line break

**Comment by astrit** [comment]
You need to place that on a div with display flex or grid and position correctly how you want, by default it doesn't have any styling.

**Comment by elburro1887** [comment]
Thanks for the update! If thats how it works, fair enough.

I like your icons, but I ended up choosing another icon library since they supported this behaviour out of the box.
